name: "YAML Feed Generator"
author: "Emanuel Poblano"
decription: "Action that generates a podcast feed from a YAML file, hosted by Github pages."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    decription: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    decription: The commiter's name
    required: true
    default: ${{ github.actor }}
